### ISSUE TITLE
Flaptpak support

### ISSUE THREAD

**Issue by fzwoch** [fzwoch/obs-teleport#104]
Looking for someone interesting in creating/maintaining Flatpak support.

People have been doing so for other plugins. See:
https://github.com/flathub/com.obsproject.Studio.Plugin.Gstreamer
https://github.com/flathub/com.obsproject.Studio.Plugin.GStreamerVaapi/

How the plugin can be build can be seen as an example from the Arch AUR:
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=obs-teleport

**Comment by Renari** [comment]
Took a look at this today for a bit, it seems Flatpak doesn't support a go SDK, however freedesktop ships an extension for it.

```sh
flatpak install flathub org.freedesktop.Platform//24.08 org.freedesktop.Sdk//24.08 org.freedesktop.Sdk.Extension.golang//24.08
```

<details>

<summary>com.obsproject.Studio.Plugin.Teleport.yaml</summary>

```yml
id: com.obsproject.Studio.Plugin.Teleport
branch: stable
runtime: com.obsproject.Studio
runtime-version: stable
sdk: org.freedesktop.Sdk//24.08
sdk-extensions:
  - org.freedesktop.Sdk.Extension.golang
build-extension: true
separate-locales: false
appstream-compose: false
build-options:
  prefix: /app/plugins/Teleport
  libdir: lib/obs-plugins
  env:
    - GOBIN=/app/bin
    - GOPATH=/run/build/obs-teleport/go
  append-path: /usr/lib/sdk/golang/bin
modules:
  - name: obs-teleport
    buildsystem: simple
    build-commands:
      - cd $FLATPAK_BUILDER_BUILDDIR && go build -ldflags "-compressdwarf=false -linkmode external -X main.version=0.7.4" -v -o "obs-teleport.so" .
    sources:
      - type: git
        url: https://github.com/fzwoch/obs-teleport.git
        tag: 0.7.4
        commit: 3e012bdcde3c8609cc89f1ede6225e30c89451ab
        x-checker-data:
          type: git
          tag-pattern: ^([\d.]+)
      - type: file
        path: com.obsproject.Studio.Plugin.Teleport.metainfo.xml
```

</details>

This gets a build up and running but it ultimately fails downloading go dependencies.

```
go: downloading github.com/schollz/peerdiscovery v1.7.6
announcer.go:28:2: github.com/schollz/peerdiscovery@v1.7.6: Get "https://proxy.golang.org/github.com/schollz/peerdiscovery/@v/v1.7.6.zip": dial tcp: lookup proxy.golang.org on 127.0.0.53:53: read udp 127.0.0.1:44821->127.0.0.53:53: read: connection refused
Error: module obs-teleport: Child process exited with code 1
```
